<a href="https://colab.research.google.com/github/arjundiwakar/python_tutorial/blob/main/2_Task_13_numpy_solution.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Note: In Data Science googling is a very important skill. If you find some difficulties to solve the problem, google it and try to find some clues to solve.**

In [1]:
import numpy as np

###`Q-1` Create a null vector of size 10 but the fifth value which is 1.



In [2]:
#Code here
a = np.nan * np.empty(10)
a[4] = 1
a

array([nan, nan, nan, nan,  1., nan, nan, nan, nan, nan])

###`Q-2` Ask user to input two numbers a, b. Write a program to generate a random array of shape (a, b) and print the array and avg of the array.

In [5]:
#Code here
a = int(input("Enter the number a : "))
b = int(input("Enter the number b : "))
arr = np.random.random((a,b))
print(arr)
print(arr.mean())

Enter the number a : 4
Enter the number b : 4
[[0.88468421 0.25113596 0.34768502 0.95496063]
 [0.45346638 0.84806193 0.78437359 0.4506246 ]
 [0.03794623 0.84257594 0.57360367 0.33312546]
 [0.32406349 0.03870663 0.77447782 0.48901218]]
0.5242814847728262


In [6]:
a,b = map(int,input("enter two numbers : ").split())


enter two numbers : 5 5


###`Q-3`Write a function to create a 2d array with 1 on the border and 0 inside. Take 2-D array shape as (a,b) as parameter to function.

Eg.-
```
[[1,1,1,1],
[1,0,0,1],
[1,0,0,1],
[1,1,1,1]]
```

In [7]:
#Code here
a, b = map(int , input("Enter the numbers : ").split())
arr = np.ones((a,b))
arr[1:a-1,1:b-1] = 0
arr  # this is not correct because we have asked to solve by making function

Enter the numbers : 5 5


array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [8]:
def border_arr(a,b):
  x = np.ones((a,b))
  x[1:-1,1:-1] = 0;
  return x

border_arr(5,5)

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

###`Q-4` Create a vector of size 10 with values ranging from 0 to 1, both excluded.


In [10]:
#Code here
np.random.random(10)   # it can includes 0 and 1 so we dont have control

array([0.78323738, 0.37795775, 0.70930709, 0.51863467, 0.03187254,
       0.207351  , 0.94575454, 0.02279066, 0.9515074 , 0.05050061])

In [14]:
# so we will use linspace to print a vector in given range -->
np.linspace(0,1,12)[1:-1]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

###`Q-5` Can you create a identity mattrix of shape (3,4). If yes write code for it.

In [18]:
#Code here
# cannot create identity matrix becoz identity matrix is always square matrix

np.eye(3)
#OR
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

###`Q-6:` Create a 5x5 matrix with row values ranging from 0 to 4.

In [27]:
#Code here
a = np.arange(0,5)

In [28]:
b = np.zeros((5,5))
b

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [29]:
b += a
b

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

For column

In [31]:
x = np.arange(5).reshape(5,1)
x

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [33]:
y = np.zeros((5,5))
y += x
y

array([[0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4.]])

###`Q-7:`  Consider a random integer (in range 1 to 100) vector with shape `(10,2)` representing coordinates, and coordinates of a point as array is given. Create an array of distance of each point in the random vectros from the given point. Distance array should be interger type.

```
point = np.array([2,3])
```


In [38]:
import math

In [43]:
#code here
point = np.array([2,3])
vector = np.random.randint(2,100,(10,2))
dist_arr = []
for vec in vector:
  distance = math.sqrt((vec[0] - point[0])**2 + (vec[1] - point[1])**2)
  dist_arr.append(int(distance))

dist_arr

[33, 69, 90, 131, 96, 95, 93, 87, 105, 86]

In [50]:
point = np.array([2,3])
vector = np.random.randint(2,100,(10,2))
print(vector-point)
np.sqrt(np.sum((vector - point)**2,axis=1)).astype(int)

[[65 56]
 [95 57]
 [57 82]
 [25 36]
 [70 95]
 [ 4 57]
 [17 27]
 [23  2]
 [62 80]
 [37 65]]


array([ 85, 110,  99,  43, 118,  57,  31,  23, 101,  74])

###`Q-8:` Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [54]:
#Code here
coord = np.unravel_index(100,(6,7,8))
print(coord)

(np.int64(1), np.int64(5), np.int64(4))


### `Q-9:` Arrays

You are given a space separated list of numbers. Your task is to print a reversed NumPy array with the element type float.



**Input Format:**

A single line of input containing space separated numbers.

**Output Format:**

Print the reverse NumPy array with type float.

**Example 1:**

Input:

```bash
1 2 3 4 -8 -10
```

Output:

```bash
[-10.  -8.   4.   3.   2.   1.]
```

In [64]:
#Code here
a = input().strip().split()
reversed_arr =np.array(a[::-1],dtype = float)
reversed_arr

2 3 4


array([4., 3., 2.])

### `Q-10:` Elements count

Count the number of elements of a numpy array.



**Example 1:**

Input:
```bash
np.array([])
```

Output:
```bash
elements_count :  0
```

**Example 2:**

Input:
```bash
np.array([1, 2])
```

Output:
```bash
elements_count :  2
```

In [66]:
#Code here
a = np.array([1,2])
a.size

2

### `Q-11:` Softmax function

Create a Python function to calculate the Softmax of the given numpy 1D array. The function only accepts the numpy 1D array, otherwise raise error.

$$\Large \sigma(\vec z)_i = \frac{e^{z_i}}{\sum_{j=i}^{K}{e^{z_j}}}$$

https://en.wikipedia.org/wiki/Softmax_function



**Example 1:**

Input:
```bash
[86.03331084 37.7285648  48.64908087 87.16563062 38.40852563 37.20006318]
```

Output:
```bash
[2.43733249e-01, 2.56112115e-22, 1.41628284e-17, 7.56266751e-01,
       5.05514197e-22, 1.50974911e-22]
```

**Example 2:**

Input:
```bash
[33.17344305 45.61961654 82.05405781 80.9647098  68.82830233 91.52064278]
```

Output:
```bash
[4.57181035e-26, 1.16249923e-20, 7.73872596e-05, 2.60358426e-05,
       1.39571531e-10, 9.99896577e-01]
```

In [71]:
#Code here
def softmax(arr):
  if type(arr) != np.ndarray:
    raise TypeError("Requires numpy array")
  elif arr.ndim > 1:
    raise TypeError("requires 1D array")
  s = np.sum(np.exp(arr))
  return np.exp(arr)/s

softmax(np.array([33.17344305, 45.61961654 ,82.05405781 ,80.9647098,  68.82830233, 91.52064278]))

array([4.57181033e-26, 1.16249922e-20, 7.73872594e-05, 2.60358426e-05,
       1.39571531e-10, 9.99896577e-01])

### `Q-12:` Vertical stack

Write a python function that accepts infinite number of numpy arrays and do the vertical stack to them. Then return that new array as result. The function only accepts the numpy array, otherwise raise error.



**Example 1:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]
```

Output:

```bash
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
```

**Example 2:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]

c= [[0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

Output:
```bash
[[0.         1.         2.         3.         4.        ]
 [5.         6.         7.         8.         9.        ]
 [1.         1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.        ]
 [0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

In [91]:
#Coder here
def v_stack(*args):
  for i in args:
    if type(i) != np.ndarray:
      raise TypeError("Requires Numpy Array")
  return np.vstack(args)

a = np.arange(10).reshape(2,-1)
print("a = ",a)
b = np.repeat(1,10).reshape(2,5)
print("b = ",b)
c = np.random.randint(0,10,(2,5))
print("c = ",c)
print(v_stack(a,b,c))

a =  [[0 1 2 3 4]
 [5 6 7 8 9]]
b =  [[1 1 1 1 1]
 [1 1 1 1 1]]
c =  [[0 7 6 5 1]
 [9 6 2 8 1]]
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [0 7 6 5 1]
 [9 6 2 8 1]]


### `Q-13:` Dates

Create a python function named **date_array** that accepts two dates as string format and returns a numpy array of dates between those 2 dates. The function only accept 2 strings, otherwise raise error. The date format should be like this only: `2022-12-6`. The end date should be included and for simplicity, choose dates from a same year.



**Example 1:**

Input:
```bash
date_array(start = '2020-09-15', end = '2020-09-25')
```

Output:
```bash
['2020-09-15', '2020-09-16', '2020-09-17', '2020-09-18',
 '2020-09-19', '2020-09-20', '2020-09-21', '2020-09-22',
 '2020-09-23', '2020-09-24', '2020-09-25']
```

**Example 2:**

Input:
```bash
date_array(start = '2022-12-01', end = '2022-12-06')
```

Output:
```bash
['2022-12-01', '2022-12-02', '2022-12-03', '2022-12-04', '2022-12-05', '2022-12-06']
```

**Example 3:**

Input:
```bash
date_array(start = '2020-11-25', end = '2020-11-30')
```

Output:
```bash
['2020-11-25', '2020-11-26', '2020-11-27', '2020-11-28',
 '2020-11-29', '2020-11-30']
```

In [ ]:
#Code here

###`Q-14:` Subtract the mean of each row from a matrix.

In [99]:
#code here
a = np.random.random([4,5])
print(a)
print(a.mean(axis = 1).reshape(4,1))  # can use keepdims = true parameter
a - a.mean(axis = 1).reshape(4,1)

[[0.8227043  0.28734526 0.42742395 0.70104054 0.20548027]
 [0.46777651 0.23915975 0.79860936 0.52184973 0.8504836 ]
 [0.90447171 0.63717438 0.58416479 0.72207963 0.38347985]
 [0.11174626 0.8185042  0.44241825 0.91128231 0.26025593]]
[[0.48879887]
 [0.57557579]
 [0.64627407]
 [0.50884139]]


array([[ 0.33390544, -0.2014536 , -0.06137491,  0.21224167, -0.28331859],
       [-0.10779928, -0.33641604,  0.22303357, -0.05372606,  0.27490781],
       [ 0.25819764, -0.00909969, -0.06210928,  0.07580556, -0.26279422],
       [-0.39709513,  0.30966281, -0.06642314,  0.40244092, -0.24858546]])

###`Q-15:` Swap column-1 of array with column-2 in the array.

In [102]:
#Code here
a = np.arange(9).reshape(3,3)
a[:,[0,2,1]]

array([[0, 2, 1],
       [3, 5, 4],
       [6, 8, 7]])

###`Q-16:` Replace odd elements in arrays with -1.

In [108]:
#Code here
a = np.arange(10)
a[a%2 != 0] = -1
a

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

###`Q-17:` Given two arrays of same shape make an array of max out of two arrays. (Numpy way)
```
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])

Result-> [6 3 1 7 8]
```

In [112]:
#Code here
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])
b[b<a] = a[a>b]
b

array([6, 3, 1, 7, 8])

###`Q-18` Answer below asked questions on given array:
1. Fetch Every alternate column of the array
2. Normalise the given array

https://en.wikipedia.org/wiki/Normalization_(statistics)

There are different form of normalisation for this question use below formula.

$$\large X_{normalized} = \frac{X - X_{min}}{X_{max} - X_{min}}$$

```python
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
```


In [113]:
# Given
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
arr1

array([[6162,  933, 5462, 8741, 6226],
       [2713, 3855,   36, 9443, 3630],
       [8559, 5556, 9816, 7147, 9029],
       [9782, 6028, 3192, 7060, 1774],
       [3019, 8515, 8847, 4751, 9375],
       [9111, 3852, 1043, 7381, 2305],
       [9893, 9350, 7721, 3672, 1601],
       [1542, 4462, 6987, 1410, 4183]])

In [115]:
#Code here
arr1[:,::2]

array([[6162, 5462, 6226],
       [2713,   36, 3630],
       [8559, 9816, 9029],
       [9782, 3192, 1774],
       [3019, 8847, 9375],
       [9111, 1043, 2305],
       [9893, 7721, 1601],
       [1542, 6987, 4183]])

In [117]:
(arr1 - arr1.min())/(arr1.max() - arr1.min())

array([[0.62148727, 0.09100132, 0.55047175, 0.88312874, 0.62798012],
       [0.27158365, 0.3874404 , 0.        , 0.95434716, 0.36461398],
       [0.86466471, 0.56000812, 0.99218829, 0.72141625, 0.91234656],
       [0.98873897, 0.60789287, 0.32017855, 0.71259004, 0.1763214 ],
       [0.30262757, 0.86020087, 0.89388252, 0.47834027, 0.94744851],
       [0.92066552, 0.38713605, 0.1021609 , 0.74515573, 0.23019174],
       [1.        , 0.94491225, 0.77964898, 0.36887491, 0.15877042],
       [0.15278482, 0.449021  , 0.70518413, 0.13939332, 0.42071624]])

###`Q-19:` Write a function which will accept 2 arguments.
First: A 1D numpy array arr

Second: An integer n {Please make sure n<=len(arr)}

Output: The output should be the nth largest item out of the array
```
# Example1 : arr=(12,34,40,7,1,0) and n=3, the output should be 12
# Example2 : arr=(12,34,40,7,1,0) and n=1, the output should be 40
```

In [126]:
#Code here
def nthmax(arr,n):
  if type(arr) != np.ndarray:
    raise TypeError("Requires Numpy array")
  elif n > len(arr):
    raise IndexError("n is way out of the limit")
  arr.sort()
  print(arr[-n])

nthmax(np.array([12,34,40,7,1,0]),1)

40


###`Q-20:` Create the following pattern without hardcoding. Use only numpy functions and the below input array a.
```
# Input: a = np.array([1,2,3])
# Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
```

In [133]:
#code here
a = np.array([1,2,3])
np.hstack((np.repeat(a,3),np.tile(a,3)))

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])