<a href="https://colab.research.google.com/github/arjundiwakar/python_tutorial/blob/main/session_15_numpy_tricks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### np.sort

Return a sorted copy of an array.

https://numpy.org/doc/stable/reference/generated/numpy.sort.html

In [2]:
# code
import numpy as np
a = np.random.randint(1,100,15)
a

array([71, 90, 68, 91, 44, 15, 56, 80, 42, 24,  4,  7, 53, 23, 43])

In [3]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[62, 77, 82, 97],
       [78, 17, 60, 63],
       [63, 65, 50, 61],
       [77, 38,  2, 50],
       [36, 77, 26, 64],
       [69,  7, 37,  1]])

In [5]:
np.sort(a)

array([ 4,  7, 15, 23, 24, 42, 43, 44, 53, 56, 68, 71, 80, 90, 91])

In [6]:
np.sort(a)[::-1]  #--> descending order sorting

array([91, 90, 80, 71, 68, 56, 53, 44, 43, 42, 24, 23, 15,  7,  4])

In [8]:
np.sort(b,axis=0)  # columnwise sorting for row wise axis = 1(it is by default)

array([[36,  7,  2,  1],
       [62, 17, 26, 50],
       [63, 38, 37, 61],
       [69, 65, 50, 63],
       [77, 77, 60, 64],
       [78, 77, 82, 97]])

### np.append

The numpy.append() appends values along the mentioned axis at the end of the array

https://numpy.org/doc/stable/reference/generated/numpy.append.html

In [9]:
# code
np.append(a,200)

array([ 71,  90,  68,  91,  44,  15,  56,  80,  42,  24,   4,   7,  53,
        23,  43, 200])

In [10]:
b

array([[62, 77, 82, 97],
       [78, 17, 60, 63],
       [63, 65, 50, 61],
       [77, 38,  2, 50],
       [36, 77, 26, 64],
       [69,  7, 37,  1]])

In [11]:
np.append(b,np.ones((b.shape[0],1)),axis=1)

array([[62., 77., 82., 97.,  1.],
       [78., 17., 60., 63.,  1.],
       [63., 65., 50., 61.,  1.],
       [77., 38.,  2., 50.,  1.],
       [36., 77., 26., 64.,  1.],
       [69.,  7., 37.,  1.,  1.]])

In [12]:
np.append(b,np.random.random((b.shape[0],1)),axis=1)

array([[62.        , 77.        , 82.        , 97.        ,  0.20869896],
       [78.        , 17.        , 60.        , 63.        ,  0.53080585],
       [63.        , 65.        , 50.        , 61.        ,  0.65540368],
       [77.        , 38.        ,  2.        , 50.        ,  0.58302826],
       [36.        , 77.        , 26.        , 64.        ,  0.43767116],
       [69.        ,  7.        , 37.        ,  1.        ,  0.95183709]])

### np.concatenate

numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

In [13]:
# code
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [14]:
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [15]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

### np.unique

With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

https://numpy.org/doc/stable/reference/generated/numpy.unique.html/

In [16]:
# code
e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])

In [18]:
np.unique(e)  # more useful

array([1, 2, 3, 4, 5, 6])

### np.expand_dims

With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array

https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html

In [19]:
# code
a.shape

(15,)

In [20]:
np.expand_dims(a,axis=0).shape

(1, 15)

In [24]:
np.expand_dims(a,axis=1)   # method of creating row vector and column vector

array([[71],
       [90],
       [68],
       [91],
       [44],
       [15],
       [56],
       [80],
       [42],
       [24],
       [ 4],
       [ 7],
       [53],
       [23],
       [43]])

In [25]:
np.expand_dims(a,axis=1).shape

(15, 1)

### np.where

The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

https://numpy.org/doc/stable/reference/generated/numpy.where.html

In [ ]:
a

array([11, 53, 28, 50, 38, 37, 94, 92,  5, 30, 68,  9, 78,  2, 21])

In [ ]:
# find all indices with value greater than 50
np.where(a>50)

(array([ 1,  6,  7, 10, 12]),)

In [ ]:
# replace all values > 50 with 0
np.where(a>50,0,a)

array([11,  0, 28, 50, 38, 37,  0,  0,  5, 30,  0,  9,  0,  2, 21])

In [ ]:
np.where(a%2 == 0,0,a)

array([11, 53,  0,  0,  0, 37,  0,  0,  5,  0,  0,  9,  0,  0, 21])

### np.argmax

The numpy.argmax() function returns indices of the max element of the array in a particular axis.

https://numpy.org/doc/stable/reference/generated/numpy.argmax.html

In [ ]:
# code
a

array([11, 53, 28, 50, 38, 37, 94, 92,  5, 30, 68,  9, 78,  2, 21])

In [ ]:
np.argmax(a)

6

In [ ]:
b

array([[12, 52, 42,  6],
       [29, 18, 47, 55],
       [61, 93, 83,  9],
       [38, 63, 44, 85],
       [ 8, 87, 31, 72],
       [40, 71,  2,  7]])

In [ ]:
np.argmax(b,axis=0)

array([2, 2, 2, 3])

In [ ]:
np.argmax(b,axis=1)

array([1, 3, 1, 3, 1, 1])

In [ ]:
# np.argmin
np.argmin(a)

13

### np.cumsum

numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html

In [ ]:
a

array([11, 53, 28, 50, 38, 37, 94, 92,  5, 30, 68,  9, 78,  2, 21])

In [ ]:
np.cumsum(a)

array([ 11,  64,  92, 142, 180, 217, 311, 403, 408, 438, 506, 515, 593,
       595, 616])

In [ ]:
b

array([[12, 52, 42,  6],
       [29, 18, 47, 55],
       [61, 93, 83,  9],
       [38, 63, 44, 85],
       [ 8, 87, 31, 72],
       [40, 71,  2,  7]])

In [ ]:
np.cumsum(b,axis=1)

array([[ 12,  64, 106, 112],
       [ 29,  47,  94, 149],
       [ 61, 154, 237, 246],
       [ 38, 101, 145, 230],
       [  8,  95, 126, 198],
       [ 40, 111, 113, 120]])

In [ ]:
np.cumsum(b)

array([  12,   64,  106,  112,  141,  159,  206,  261,  322,  415,  498,
        507,  545,  608,  652,  737,  745,  832,  863,  935,  975, 1046,
       1048, 1055])

In [ ]:
# np.cumprod
np.cumprod(a)

array([                  11,                  583,                16324,
                     816200,             31015600,           1147577200,
               107872256800,        9924247625600,       49621238128000,
           1488637143840000,   101227325781120000,   911045932030080000,
       -2725393596491966464, -5450787192983932928, -3786066610405281792])

In [ ]:
a

array([11, 53, 28, 50, 38, 37, 94, 92,  5, 30, 68,  9, 78,  2, 21])

### np.percentile

numpy.percentile()function used to compute the nth percentile of the given data (array elements) along the specified axis.

https://numpy.org/doc/stable/reference/generated/numpy.percentile.html

In [ ]:
a

array([11, 53, 28, 50, 38, 37, 94, 92,  5, 30, 68,  9, 78,  2, 21])

In [ ]:
np.percentile(a,50)

37.0

In [ ]:
np.median(a)

37.0

### np.histogram

Numpy has a built-in numpy.histogram() function which represents the frequency of data distribution in the graphical form.

https://numpy.org/doc/stable/reference/generated/numpy.histogram.html

In [ ]:
# code
a

array([11, 53, 28, 50, 38, 37, 94, 92,  5, 30, 68,  9, 78,  2, 21])

In [ ]:
np.histogram(a,bins=[0,50,100])

(array([9, 6]), array([  0,  50, 100]))

### np.corrcoef

Return Pearson product-moment correlation coefficients.

https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html

In [ ]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

### np.isin

With the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.

https://numpy.org/doc/stable/reference/generated/numpy.isin.html

In [27]:
# code
a


array([71, 90, 68, 91, 44, 15, 56, 80, 42, 24,  4,  7, 53, 23, 43])

In [28]:
items = [10,20,30,40,50,60,70,80,90,100]

a[np.isin(a,items)] # can search multiple items at a time.

array([90, 80])

### np.flip

The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.

https://numpy.org/doc/stable/reference/generated/numpy.flip.html

In [32]:
# code
a

array([71, 90, 68, 91, 44, 15, 56, 80, 42, 24,  4,  7, 53, 23, 43])

In [33]:
np.flip(a)

array([43, 23, 53,  7,  4, 24, 42, 80, 56, 15, 44, 91, 68, 90, 71])

In [34]:
b

array([[62, 77, 82, 97],
       [78, 17, 60, 63],
       [63, 65, 50, 61],
       [77, 38,  2, 50],
       [36, 77, 26, 64],
       [69,  7, 37,  1]])

In [35]:
np.flip(b,axis=1)

array([[97, 82, 77, 62],
       [63, 60, 17, 78],
       [61, 50, 65, 63],
       [50,  2, 38, 77],
       [64, 26, 77, 36],
       [ 1, 37,  7, 69]])

### np.put

The numpy.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array.

https://numpy.org/doc/stable/reference/generated/numpy.put.html

In [38]:
# code
a

array([110, 530,  68,  91,  44,  15,  56,  80,  42,  24,   4,   7,  53,
        23,  43])

In [37]:
np.put(a,[0,1],[110,530]) #changes permanent

### np.delete

The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis.

https://numpy.org/doc/stable/reference/generated/numpy.delete.html

In [39]:
# code
a

array([110, 530,  68,  91,  44,  15,  56,  80,  42,  24,   4,   7,  53,
        23,  43])

In [40]:
np.delete(a,0)

array([530,  68,  91,  44,  15,  56,  80,  42,  24,   4,   7,  53,  23,
        43])

In [41]:
np.delete(a,[0,2,4])

array([530,  91,  15,  56,  80,  42,  24,   4,   7,  53,  23,  43])

### Set functions

- np.union1d
- np.intersect1d
- np.setdiff1d
- np.setxor1d
- np.in1d

In [42]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [43]:
np.intersect1d(m,n)

array([3, 4, 5])

In [44]:
np.setdiff1d(n,m)

array([6, 7])

In [46]:
np.setxor1d(m,n) # remove common from both

array([1, 2, 6, 7])

In [49]:
np.in1d(m,1) # check if item present or not

<ipython-input-49-38a38f93d3b6>:1: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  np.in1d(m,1) # check if item present or not


array([ True, False, False, False, False])

In [50]:
m[np.in1d(m,1)]

<ipython-input-50-3d5a78555eb5>:1: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  m[np.in1d(m,1)]


array([1])

### np.clip

numpy.clip() function is used to Clip (limit) the values in an array.

https://numpy.org/doc/stable/reference/generated/numpy.clip.html

In [51]:
# code
a

array([110, 530,  68,  91,  44,  15,  56,  80,  42,  24,   4,   7,  53,
        23,  43])

In [52]:
np.clip(a,a_min=25,a_max=75)  # all values will be in range 25 and 75 after execution

array([75, 75, 68, 75, 44, 25, 56, 75, 42, 25, 25, 25, 53, 25, 43])

In [ ]:
# 17. np.swapaxes

In [ ]:
# 18. np.uniform

In [ ]:
# 19. np.count_nonzero

In [ ]:
# 21. np.tile
# https://www.kaggle.com/code/abhayparashar31/best-numpy-functions-for-data-science-50?scriptVersionId=98816580

In [ ]:
# 22. np.repeat
# https://towardsdatascience.com/10-numpy-functions-you-should-know-1dc4863764c5

In [ ]:

# 25. np.allclose and equals